#!/usr/bin/env python
import sys
import time
from IPv4 Parser_class.py import *
def expand(x):
	yield x
	while x.payload:
		x = x.payload
		yield x
def handle_pkt(pkt):
	if pkt[Ethernet].type == IPv4:
		print(pkt.show())
iface = 'eth0'
if len(sys.argv) > 1:
	iface = sys.argv[1]
print "sniffing on {}".format(iface)
sniff(iface = iface, prn = lambda x: handle_pkt(x))

